apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-flask-app
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      securityContext:
        runAsUser: 3000
      containers:
      - image: hgokcedag/server-flask:latest
        name: server-flask
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-flask-app
  name: my-flask-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30300
  selector:
    app: my-flask-app
  type: NodePort
  